rbr_source_cluster: refresh_primary

schema_tracker_cluster: repltracker

rbr_state_cluster: replhandler

register_dry_run: True

publish_dry_run: True

topology_path: topology.yaml

changelog_schemaname: changelog.v2

changelog_mode: False

schema_blacklist:
    - information_schema
    - mysql
    - performance_schema
    - test

producer_name: replication_handler

team_name: bam

zookeeper_discovery_path: '/nail/etc/zookeeper_discovery/generic/uswest2{ecosystem}.yaml'

pii_yaml_path: '/nail/etc/services/database_pii'

max_delay_allowed_in_seconds: 600

sensu_host: 169.254.255.254

disable_sensu: False

disable_meteorite: False

recovery_queue_size: 1500

namespace: dev

container_name: none

container_env: raw

force_exit: False
